# dannyh79's .zshrc (2024-06-07 22:39:43 +0800)
# You can reach me on https://github.com/dannyh79/
# Enjoy :)

# 2021-12-09 10:32:34 +0800 move this part up top
# gpg terminal patch for git (problem occured since 11/01, '19)
# this is to set "GPG_TTY environment variable"
# found in https://juliansimioni.com/blog/troubleshooting-gpg-git-commit-signing/
export GPG_TTY=$(tty)

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Ref: https://gist.github.com/matthewmccullough/787142
setopt appendhistory
setopt sharehistory
setopt incappendhistory
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

bindkey -v
bindkey -e


# You may need to manually set your language environment
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8


# Gaming
# needs to be used under x86, i.e., `$ arch -x86_64 zsh`
wine-gptk(){ WINEESYNC=1 WINEPREFIX=~/my-windows-gaming $(brew --prefix game-porting-toolkit)/bin/wine64 "$@"; }

# auto switch macOS brew path by arch
if [ "$(uname)" = "Darwin" ]; then
  if [ "$(arch)" = "arm64" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  else
    eval "$(/usr/local/bin/brew shellenv)"
  fi
fi

source "$HOME/.config/zsh/internal/load_every_file_in_dir.zsh"
source "$HOME/.config/zsh/internal/add_to_path.zsh"

PATH_ENTRIES=()

# Etc
etc_dir="$HOME/.config/zsh/etc"
load_every_file_in_dir $etc_dir

add_to_path "${PATH_ENTRIES[@]}"

# Aliases
# TODO: set up auto install for the bins
aliases_dir="$HOME/.config/zsh/aliases"
load_every_file_in_dir $aliases_dir

# Tab completion for git
# Ref: https://git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-Zsh
autoload -Uz compinit && compinit
